# Change these first
owner: ahernandez411 # Your GitHub organization or username, where this repository lives
repo: upptime-testing # The name of this repository

sites:
  - name: API Limit Check (Me)
    url: https://api.github.com/rate_limit
    method: GET
    headers:
      - "Accept: application/vnd.github+json"
      - "Authorization: Bearer $GH_PAT"
      - "X-GitHub-Api-Version: 2022-11-28"
    expectedStatusCodes:
      - 200

  - name: API Limit Check (Other)
    url: https://api.github.com/rate_limit
    method: GET
    headers:
      - "Accept: application/vnd.github+json"
      - "Authorization: Bearer $GH_PAT_2"
      - "X-GitHub-Api-Version: 2022-11-28"
    expectedStatusCodes:
      - 200


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime-testing
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: UppTime Testing
  introTitle: "This is a test status page"
  introMessage: Nothing special to say here. Testing to see how this works! Did not work last time.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
